export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_ERROR = 'FETCH_MEMBERS_ERROR';
export const FETCH_MEMBER_DETAIL_SUCCESS = 'FETCH_MEMBER_DETAIL_SUCCESS';
export const FETCH_MEMBER_DETAIL_ERROR = 'FETCH_MEMBER_DETAIL_ERROR';