// CREATE NEW
export const CREATE_NEW_REQUEST = 'CREATE_NEW_REQUEST';
export const CREATE_NEW_SUCCESS = 'CREATE_NEW_SUCCESS';
export const CREATE_NEW_ERROR = 'CREATE_NEW_ERROR';

// FORMULA
export const FETCH_FORMULAS_REQUEST = 'FETCH_FORMULAS_REQUEST';
export const FETCH_FORMULAS_SUCCESS = 'FETCH_FORMULAS_SUCCESS';
export const FETCH_FORMULAS_ERROR = 'FETCH_FORMULAS_ERROR';
export const FETCH_FORMULA_DETAIL_SUCCESS = 'FETCH_FORMULA_DETAIL_SUCCESS';
export const FETCH_FORMULA_DETAIL_ERROR = 'FETCH_FORMULA_DETAIL_ERROR';

// MEMBER
export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_ERROR = 'FETCH_MEMBERS_ERROR';
export const FETCH_MEMBER_DETAIL_SUCCESS = 'FETCH_MEMBER_DETAIL_SUCCESS';
export const FETCH_MEMBER_DETAIL_ERROR = 'FETCH_MEMBER_DETAIL_ERROR';

export const SAVE_MEMBER_SUCCESS = 'SAVE_MEMBER_SUCCESS';
export const SAVE_MEMBER_ERROR = 'SAVE_MEMBER_ERROR';

// ACCOUNT
export const FETCH_ACCOUNTS_REQUEST = 'FETCH_ACCOUNTS_REQUEST';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_ERROR = 'FETCH_ACCOUNTS_ERROR';
export const FETCH_ACCOUNT_DETAIL_SUCCESS = 'FETCH_ACCOUNT_DETAIL_SUCCESS';
export const FETCH_ACCOUNT_DETAIL_ERROR = 'FETCH_ACCOUNT_DETAIL_ERROR';